### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by alayek** [fcc-hyd/gitStory#1]
Following are the resources in order of increasing complexity:

- [Udacity Git and GitHub](https://www.udacity.com/course/how-to-use-git-and-github--ud775)
- [GitHub flow](https://guides.github.com/introduction/flow/)
- [Git Tutorials](https://www.atlassian.com/git/)

**Comment by rhhhhl** [comment]
@alayek Any Links on R.S.A and S.S.H keys to set-up on our pc ? are they necessary to config git ?

**Comment by khaledMohammed000** [comment]
Yes instead of spending several hours trying figure out from Udacity's tutorial , I have created a summary of the same course...the other two links are great..they can go through the initial content of through any tutorial online to familiarize with the process
